const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

const foods = [
  // === PROTEINS ===
  { id:"p1", name:"Peito de frango grelhado", category:"protein", kcal:159, prot:32, carb:0, fat:3.2, mealTypes:["principal"], subGroup:"ave_magra" },
  { id:"p2", name:"Coxa de frango s/ pele", category:"protein", kcal:163, prot:26, carb:0, fat:6.5, mealTypes:["principal"], subGroup:"ave" },
  { id:"p3", name:"Peito de peru defumado", category:"protein", kcal:130, prot:21, carb:2.5, fat:3.8, mealTypes:["cafe","lanche"], subGroup:"frio" },
  { id:"p4", name:"Patinho grelhado", category:"protein", kcal:219, prot:35.9, carb:0, fat:7.3, mealTypes:["principal"], subGroup:"bovina_magra" },
  { id:"p5", name:"Maminha grelhada", category:"protein", kcal:212, prot:32.4, carb:0, fat:8.5, mealTypes:["principal"], subGroup:"bovina" },
  { id:"p6", name:"Alcatra grelhada", category:"protein", kcal:235, prot:32, carb:0, fat:11, mealTypes:["principal"], subGroup:"bovina" },
  { id:"p7", name:"Coxão mole grelhado", category:"protein", kcal:215, prot:32.4, carb:0, fat:8.9, mealTypes:["principal"], subGroup:"bovina" },
  { id:"p8", name:"Músculo cozido", category:"protein", kcal:171, prot:26.8, carb:0, fat:6.7, mealTypes:["principal"], subGroup:"bovina" },
  { id:"p9", name:"Lagarto grelhado", category:"protein", kcal:206, prot:33.4, carb:0, fat:7.5, mealTypes:["principal"], subGroup:"bovina_magra" },
  { id:"p10", name:"Filé mignon grelhado", category:"protein", kcal:220, prot:32.8, carb:0, fat:9.5, mealTypes:["principal"], subGroup:"bovina" },
  { id:"p11", name:"Lombo suíno assado", category:"protein", kcal:210, prot:30.2, carb:0, fat:9.8, mealTypes:["principal"], subGroup:"suina" },
  { id:"p12", name:"Tilápia grelhada", category:"protein", kcal:124, prot:26.2, carb:0, fat:2, mealTypes:["principal"], subGroup:"peixe_magro" },
  { id:"p13", name:"Salmão grelhado", category:"protein", kcal:208, prot:27.3, carb:0, fat:10.5, mealTypes:["principal"], subGroup:"peixe_gordo" },
  { id:"p14", name:"Atum em conserva", category:"protein", kcal:166, prot:26.2, carb:0, fat:6.4, mealTypes:["principal","lanche"], subGroup:"peixe" },
  { id:"p15", name:"Sardinha assada", category:"protein", kcal:164, prot:25, carb:0, fat:7, mealTypes:["principal"], subGroup:"peixe" },
  { id:"p16", name:"Merluza cozida", category:"protein", kcal:89, prot:18.9, carb:0, fat:1.3, mealTypes:["principal"], subGroup:"peixe_magro" },
  { id:"p17", name:"Camarão cozido", category:"protein", kcal:90, prot:18.4, carb:0, fat:1.5, mealTypes:["principal"], subGroup:"frutos_mar" },
  { id:"p18", name:"Ovo inteiro cozido", category:"protein", kcal:146, prot:13.3, carb:0.6, fat:9.5, mealTypes:["cafe","principal","lanche"], subGroup:"ovo" },
  { id:"p19", name:"Clara de ovo", category:"protein", kcal:44, prot:9.7, carb:0.8, fat:0, mealTypes:["cafe","lanche"], subGroup:"ovo" },
  { id:"p20", name:"Queijo cottage", category:"protein", kcal:98, prot:11.5, carb:3.4, fat:4.3, mealTypes:["cafe","lanche"], subGroup:"queijo_magro" },
  { id:"p21", name:"Queijo minas frescal", category:"protein", kcal:264, prot:17.4, carb:3.2, fat:20.2, mealTypes:["cafe","lanche"], subGroup:"queijo" },
  { id:"p22", name:"Iogurte natural desnatado", category:"protein", kcal:42, prot:4.1, carb:5.6, fat:0.3, mealTypes:["cafe","lanche"], subGroup:"laticinio" },
  { id:"p23", name:"Ricota fresca", category:"protein", kcal:140, prot:12.6, carb:3.5, fat:8.1, mealTypes:["cafe","lanche"], subGroup:"queijo_magro" },
  { id:"p24", name:"Whey protein concentrado Growth (30g)", category:"protein", kcal:123, prot:23, carb:3.3, fat:2, mealTypes:["lanche","cafe"], subGroup:"suplemento" },
  { id:"p25", name:"Carne seca desfiada", category:"protein", kcal:230, prot:33.8, carb:0, fat:10.5, mealTypes:["principal"], subGroup:"bovina" },
  { id:"p26", name:"Frango desfiado", category:"protein", kcal:163, prot:31.5, carb:0, fat:3.8, mealTypes:["principal"], subGroup:"ave_magra" },
  { id:"p27", name:"Sobrecoxa s/ pele", category:"protein", kcal:183, prot:24.2, carb:0, fat:9.5, mealTypes:["principal"], subGroup:"ave" },
  { id:"p28", name:"Pintado grelhado", category:"protein", kcal:118, prot:23.5, carb:0, fat:2.8, mealTypes:["principal"], subGroup:"peixe_magro" },
  { id:"p29", name:"Carne moída magra", category:"protein", kcal:212, prot:26.7, carb:0, fat:11.5, mealTypes:["principal"], subGroup:"bovina" },
  { id:"p30", name:"Peito de pato", category:"protein", kcal:201, prot:23.5, carb:0, fat:11.5, mealTypes:["principal"], subGroup:"ave" },
  { id:"p31", name:"Coelho assado", category:"protein", kcal:173, prot:29, carb:0, fat:6, mealTypes:["principal"], subGroup:"outra" },
  { id:"p32", name:"Linguiça de frango", category:"protein", kcal:169, prot:17.5, carb:2, fat:10, mealTypes:["principal","cafe"], subGroup:"embutido" },
  { id:"p33", name:"Presunto magro", category:"protein", kcal:110, prot:16.5, carb:2, fat:4, mealTypes:["cafe","lanche"], subGroup:"frio" },
  { id:"p34", name:"Blanquet de peru", category:"protein", kcal:118, prot:19.5, carb:2.8, fat:3.2, mealTypes:["cafe","lanche"], subGroup:"frio" },
  { id:"p35", name:"Leite desnatado", category:"protein", kcal:35, prot:3.4, carb:5, fat:0.2, mealTypes:["cafe","lanche"], subGroup:"laticinio" },
  { id:"p36", name:"Tofu firme", category:"protein", kcal:76, prot:8.1, carb:1.9, fat:4.8, mealTypes:["principal","lanche"], subGroup:"vegetal" },
  { id:"p37", name:"Proteína de soja", category:"protein", kcal:330, prot:51, carb:21, fat:1, mealTypes:["principal"], subGroup:"vegetal" },
  { id:"p38", name:"Grão-de-bico cozido", category:"protein", kcal:164, prot:8.9, carb:27.4, fat:2.6, mealTypes:["principal"], subGroup:"leguminosa" },
  { id:"p39", name:"Lentilha cozida", category:"protein", kcal:93, prot:6.3, carb:16.3, fat:0.5, mealTypes:["principal"], subGroup:"leguminosa" },
  { id:"p40", name:"Feijão preto cozido", category:"protein", kcal:77, prot:4.5, carb:14, fat:0.5, mealTypes:["principal"], subGroup:"leguminosa" },
  { id:"p41", name:"Caseína (30g)", category:"protein", kcal:115, prot:23, carb:3.5, fat:1, mealTypes:["lanche","cafe"], subGroup:"suplemento" },
  { id:"p42", name:"Acém cozido", category:"protein", kcal:198, prot:26, carb:0, fat:10.2, mealTypes:["principal"], subGroup:"bovina" },
  { id:"p43", name:"Peito de frango cozido", category:"protein", kcal:151, prot:30.5, carb:0, fat:3.1, mealTypes:["principal"], subGroup:"ave_magra" },
  { id:"p44", name:"Peru assado", category:"protein", kcal:153, prot:29, carb:0, fat:4.1, mealTypes:["principal"], subGroup:"ave_magra" },
  { id:"p45", name:"Chester assado", category:"protein", kcal:158, prot:28, carb:0, fat:5, mealTypes:["principal"], subGroup:"ave" },
  { id:"p46", name:"Atum fresco grelhado", category:"protein", kcal:184, prot:29, carb:0, fat:6.5, mealTypes:["principal"], subGroup:"peixe" },
  { id:"p47", name:"Robalo grelhado", category:"protein", kcal:124, prot:24, carb:0, fat:3, mealTypes:["principal"], subGroup:"peixe_magro" },
  { id:"p48", name:"Bacalhau cozido", category:"protein", kcal:105, prot:23.8, carb:0, fat:1, mealTypes:["principal"], subGroup:"peixe_magro" },
  { id:"p49", name:"Linguado grelhado", category:"protein", kcal:117, prot:24.5, carb:0, fat:2.2, mealTypes:["principal"], subGroup:"peixe_magro" },
  { id:"p50", name:"Truta grelhada", category:"protein", kcal:177, prot:26, carb:0, fat:7.5, mealTypes:["principal"], subGroup:"peixe" },
  { id:"p51", name:"Coxão duro cozido", category:"protein", kcal:203, prot:30, carb:0, fat:8.5, mealTypes:["principal"], subGroup:"bovina" },
  { id:"p52", name:"Fígado bovino grelhado", category:"protein", kcal:191, prot:29, carb:4.9, fat:5.3, mealTypes:["principal"], subGroup:"bovina_magra" },
  { id:"p53", name:"Pernil suíno magro assado", category:"protein", kcal:196, prot:28.4, carb:0, fat:8.2, mealTypes:["principal"], subGroup:"suina" },
  { id:"p54", name:"Lombo canadense", category:"protein", kcal:142, prot:22.5, carb:1.8, fat:5, mealTypes:["cafe","lanche"], subGroup:"frio" },
  { id:"p55", name:"Skyr natural", category:"protein", kcal:63, prot:11, carb:3.8, fat:0.2, mealTypes:["cafe","lanche"], subGroup:"laticinio" },
  { id:"p56", name:"Iogurte grego zero", category:"protein", kcal:59, prot:10, carb:3.6, fat:0.1, mealTypes:["cafe","lanche"], subGroup:"laticinio" },
  { id:"p57", name:"Kefir desnatado", category:"protein", kcal:41, prot:3.5, carb:4.8, fat:0.3, mealTypes:["cafe","lanche"], subGroup:"laticinio" },
  { id:"p58", name:"Peito de frango em cubos", category:"protein", kcal:157, prot:31.2, carb:0, fat:3.5, mealTypes:["principal","lanche"], subGroup:"ave_magra" },
  { id:"p59", name:"Omelete simples", category:"protein", kcal:154, prot:11.8, carb:1.2, fat:11.1, mealTypes:["cafe","lanche"], subGroup:"ovo" },
  { id:"p60", name:"Claras pasteurizadas", category:"protein", kcal:48, prot:10.1, carb:1, fat:0, mealTypes:["cafe","lanche"], subGroup:"ovo" },
  { id:"p61", name:"Cupim assado", category:"protein", kcal:330, prot:28, carb:0, fat:24, mealTypes:["principal"], subGroup:"bovina" },
  { id:"p62", name:"Costela bovina assada", category:"protein", kcal:373, prot:26, carb:0, fat:30, mealTypes:["principal"], subGroup:"bovina" },
  { id:"p63", name:"Picanha grelhada", category:"protein", kcal:289, prot:30, carb:0, fat:19, mealTypes:["principal"], subGroup:"bovina" },
  { id:"p64", name:"Fraldinha grelhada", category:"protein", kcal:241, prot:31, carb:0, fat:13, mealTypes:["principal"], subGroup:"bovina" },
  { id:"p65", name:"Paleta bovina cozida", category:"protein", kcal:214, prot:29, carb:0, fat:10.5, mealTypes:["principal"], subGroup:"bovina" },
  { id:"p66", name:"Contrafilé grelhado", category:"protein", kcal:278, prot:31.5, carb:0, fat:17, mealTypes:["principal"], subGroup:"bovina" },
  { id:"p67", name:"Cordeiro assado", category:"protein", kcal:260, prot:28, carb:0, fat:16, mealTypes:["principal"], subGroup:"outra" },
  { id:"p68", name:"Pernil de cordeiro", category:"protein", kcal:243, prot:29, carb:0, fat:13.5, mealTypes:["principal"], subGroup:"outra" },
  { id:"p69", name:"Lombo de bacalhau", category:"protein", kcal:110, prot:24, carb:0, fat:1.2, mealTypes:["principal"], subGroup:"peixe_magro" },
  { id:"p70", name:"Cação grelhado", category:"protein", kcal:129, prot:25.6, carb:0, fat:2.8, mealTypes:["principal"], subGroup:"peixe_magro" },
  { id:"p71", name:"Mexilhão cozido", category:"protein", kcal:86, prot:11.9, carb:3.7, fat:2.2, mealTypes:["principal"], subGroup:"frutos_mar" },
  { id:"p72", name:"Lula grelhada", category:"protein", kcal:92, prot:15.6, carb:3.1, fat:1.4, mealTypes:["principal"], subGroup:"frutos_mar" },
  { id:"p73", name:"Ostras cozidas", category:"protein", kcal:81, prot:9.5, carb:4.9, fat:2.3, mealTypes:["principal"], subGroup:"frutos_mar" },
  { id:"p74", name:"Carne de siri", category:"protein", kcal:95, prot:19.3, carb:0, fat:1.5, mealTypes:["principal"], subGroup:"frutos_mar" },
  { id:"p75", name:"Coxa de pato assada", category:"protein", kcal:240, prot:23, carb:0, fat:16, mealTypes:["principal"], subGroup:"ave" },
  { id:"p76", name:"Lombo suíno grelhado", category:"protein", kcal:189, prot:29, carb:0, fat:7.8, mealTypes:["principal"], subGroup:"suina" },
  { id:"p77", name:"Bisteca suína grelhada", category:"protein", kcal:255, prot:28, carb:0, fat:15.5, mealTypes:["principal"], subGroup:"suina" },
  { id:"p78", name:"Isca de frango grelhada", category:"protein", kcal:160, prot:31, carb:0, fat:3.7, mealTypes:["principal","lanche"], subGroup:"ave_magra" },
  { id:"p79", name:"Carne moída 80/20", category:"protein", kcal:254, prot:25.5, carb:0, fat:17, mealTypes:["principal"], subGroup:"bovina" },
  { id:"p80", name:"Hambúrguer bovino artesanal", category:"protein", kcal:260, prot:24, carb:0, fat:18, mealTypes:["principal","lanche"], subGroup:"bovina" },
  { id:"p81", name:"Ovos mexidos", category:"protein", kcal:149, prot:10.4, carb:1.6, fat:10.8, mealTypes:["cafe","lanche","principal"], subGroup:"ovo" },

  // === CARBS ===
  { id:"c1", name:"Arroz branco cozido", category:"carb", kcal:128, prot:2.5, carb:28.1, fat:0.2, mealTypes:["principal"], subGroup:"arroz" },
  { id:"c2", name:"Arroz integral cozido", category:"carb", kcal:124, prot:2.6, carb:25.8, fat:1, mealTypes:["principal"], subGroup:"arroz" },
  { id:"c3", name:"Batata-doce cozida", category:"carb", kcal:77, prot:0.6, carb:18.4, fat:0.1, mealTypes:["principal"], subGroup:"tuberculo" },
  { id:"c4", name:"Batata inglesa cozida", category:"carb", kcal:52, prot:1.2, carb:11.9, fat:0.1, mealTypes:["principal"], subGroup:"tuberculo" },
  { id:"c5", name:"Mandioca cozida", category:"carb", kcal:125, prot:0.6, carb:30.1, fat:0.3, mealTypes:["principal"], subGroup:"tuberculo" },
  { id:"c6", name:"Macarrão cozido", category:"carb", kcal:102, prot:3.4, carb:19.9, fat:0.5, mealTypes:["principal"], subGroup:"massa" },
  { id:"c7", name:"Macarrão integral", category:"carb", kcal:111, prot:4.6, carb:21.8, fat:0.6, mealTypes:["principal"], subGroup:"massa" },
  { id:"c8", name:"Pão francês", category:"carb", kcal:300, prot:8, carb:58.6, fat:3.1, mealTypes:["cafe","lanche"], subGroup:"pao" },
  { id:"c9", name:"Pão integral", category:"carb", kcal:253, prot:9.4, carb:49.3, fat:2.9, mealTypes:["cafe","lanche"], subGroup:"pao" },
  { id:"c10", name:"Aveia em flocos", category:"carb", kcal:394, prot:13.9, carb:66.6, fat:8.5, mealTypes:["cafe","lanche"], subGroup:"cereal_cafe" },
  { id:"c11", name:"Banana prata", category:"carb", kcal:98, prot:1.3, carb:26, fat:0.1, mealTypes:["cafe","lanche","jantar_adj"], subGroup:"fruta" },
  { id:"c12", name:"Banana da terra cozida", category:"carb", kcal:117, prot:0.7, carb:30.9, fat:0.2, mealTypes:["principal"], subGroup:"tuberculo" },
  { id:"c13", name:"Manga", category:"carb", kcal:64, prot:0.4, carb:16.7, fat:0.3, mealTypes:["cafe","lanche","jantar_adj"], subGroup:"fruta" },
  { id:"c14", name:"Maçã", category:"carb", kcal:56, prot:0.3, carb:15.2, fat:0, mealTypes:["cafe","lanche","jantar_adj"], subGroup:"fruta" },
  { id:"c15", name:"Mamão papaia", category:"carb", kcal:40, prot:0.5, carb:10.4, fat:0.1, mealTypes:["cafe","lanche","jantar_adj"], subGroup:"fruta" },
  { id:"c16", name:"Tapioca (goma)", category:"carb", kcal:342, prot:0.1, carb:84.8, fat:0.1, mealTypes:["cafe","lanche"], subGroup:"tapioca" },
  { id:"c17", name:"Cuscuz de milho", category:"carb", kcal:113, prot:2.6, carb:23.3, fat:0.8, mealTypes:["cafe","principal"], subGroup:"cereal" },
  { id:"c18", name:"Milho verde cozido", category:"carb", kcal:131, prot:3.6, carb:28.6, fat:0.8, mealTypes:["principal"], subGroup:"cereal" },
  { id:"c19", name:"Inhame cozido", category:"carb", kcal:97, prot:2, carb:23.2, fat:0.1, mealTypes:["principal"], subGroup:"tuberculo" },
  { id:"c20", name:"Quinoa cozida", category:"carb", kcal:120, prot:4.4, carb:21.3, fat:1.9, mealTypes:["principal"], subGroup:"cereal" },
  { id:"c21", name:"Granola", category:"carb", kcal:421, prot:9.8, carb:65.2, fat:14.2, mealTypes:["cafe","lanche"], subGroup:"cereal_cafe" },
  { id:"c22", name:"Mel", category:"carb", kcal:309, prot:0.3, carb:84, fat:0, mealTypes:["cafe","lanche"], subGroup:"acucar" },
  { id:"c23", name:"Açaí polpa pura", category:"carb", kcal:58, prot:0.8, carb:6.2, fat:3.9, mealTypes:["lanche"], subGroup:"fruta" },
  { id:"c24", name:"Farinha de mandioca", category:"carb", kcal:361, prot:1.6, carb:87.9, fat:0.3, mealTypes:["principal"], subGroup:"farinaceo" },
  { id:"c25", name:"Abóbora cozida", category:"carb", kcal:28, prot:0.8, carb:7, fat:0, mealTypes:["principal"], subGroup:"legume" },
  { id:"c26", name:"Beterraba cozida", category:"carb", kcal:32, prot:1.2, carb:7.2, fat:0, mealTypes:["principal"], subGroup:"legume" },
  { id:"c27", name:"Cenoura crua", category:"carb", kcal:34, prot:1.3, carb:7.7, fat:0.2, mealTypes:["principal"], subGroup:"legume" },
  { id:"c28", name:"Pão de queijo", category:"carb", kcal:363, prot:5.3, carb:34.2, fat:23.1, mealTypes:["cafe","lanche"], subGroup:"pao" },
  { id:"c29", name:"Torrada integral", category:"carb", kcal:353, prot:12.5, carb:61.7, fat:6.8, mealTypes:["cafe","lanche"], subGroup:"pao" },
  { id:"c30", name:"Pipoca (milho)", category:"carb", kcal:374, prot:11.8, carb:64.6, fat:5.6, mealTypes:["lanche"], subGroup:"cereal_cafe" },
  { id:"c31", name:"Farinha de aveia", category:"carb", kcal:388, prot:15, carb:65, fat:7.5, mealTypes:["cafe","lanche"], subGroup:"cereal_cafe" },
  { id:"c32", name:"Mingau de aveia", category:"carb", kcal:68, prot:2.4, carb:11.8, fat:1.5, mealTypes:["cafe"], subGroup:"cereal_cafe" },
  { id:"c33", name:"Crepioca", category:"carb", kcal:190, prot:8.5, carb:20, fat:8, mealTypes:["cafe","lanche"], subGroup:"tapioca" },
  { id:"c34", name:"Wrap integral", category:"carb", kcal:280, prot:8.2, carb:46, fat:6.5, mealTypes:["lanche","principal"], subGroup:"pao" },
  { id:"c35", name:"Mandioquinha cozida", category:"carb", kcal:80, prot:0.9, carb:19.3, fat:0.2, mealTypes:["principal"], subGroup:"tuberculo" },
  { id:"c36", name:"Uva", category:"carb", kcal:53, prot:0.7, carb:13.6, fat:0.2, mealTypes:["cafe","lanche","jantar_adj"], subGroup:"fruta" },
  { id:"c37", name:"Melancia", category:"carb", kcal:33, prot:0.9, carb:8.1, fat:0, mealTypes:["cafe","lanche","jantar_adj"], subGroup:"fruta" },
  { id:"c38", name:"Abacaxi", category:"carb", kcal:48, prot:0.9, carb:12.3, fat:0.1, mealTypes:["cafe","lanche","jantar_adj"], subGroup:"fruta" },
  { id:"c39", name:"Morango", category:"carb", kcal:30, prot:0.9, carb:6.8, fat:0.3, mealTypes:["cafe","lanche","jantar_adj"], subGroup:"fruta" },
  { id:"c40", name:"Laranja", category:"carb", kcal:37, prot:1, carb:8.9, fat:0.1, mealTypes:["cafe","lanche","jantar_adj"], subGroup:"fruta" },
  { id:"c41", name:"Polenta", category:"carb", kcal:68, prot:1.5, carb:14.3, fat:0.5, mealTypes:["principal"], subGroup:"cereal" },
  { id:"c42", name:"Macarrão de arroz", category:"carb", kcal:109, prot:0.9, carb:25, fat:0.2, mealTypes:["principal"], subGroup:"massa" },
  { id:"c43", name:"Arroz parboilizado cozido", category:"carb", kcal:123, prot:2.7, carb:25.9, fat:0.3, mealTypes:["principal"], subGroup:"arroz" },
  { id:"c44", name:"Arroz negro cozido", category:"carb", kcal:145, prot:4.2, carb:31.5, fat:0.9, mealTypes:["principal"], subGroup:"arroz" },
  { id:"c45", name:"Arroz selvagem cozido", category:"carb", kcal:101, prot:4, carb:21.3, fat:0.3, mealTypes:["principal"], subGroup:"arroz" },
  { id:"c46", name:"Feijão carioca cozido", category:"carb", kcal:76, prot:4.8, carb:13.6, fat:0.5, mealTypes:["principal"], subGroup:"leguminosa" },
  { id:"c47", name:"Feijão fradinho cozido", category:"carb", kcal:78, prot:5.1, carb:13.4, fat:0.6, mealTypes:["principal"], subGroup:"leguminosa" },
  { id:"c48", name:"Ervilha cozida", category:"carb", kcal:81, prot:5.4, carb:14.5, fat:0.4, mealTypes:["principal"], subGroup:"leguminosa" },
  { id:"c49", name:"Pão sírio integral", category:"carb", kcal:275, prot:9.1, carb:55, fat:2.1, mealTypes:["cafe","lanche"], subGroup:"pao" },
  { id:"c50", name:"Pão de forma 100% integral", category:"carb", kcal:247, prot:10.2, carb:43.8, fat:4.1, mealTypes:["cafe","lanche"], subGroup:"pao" },
  { id:"c51", name:"Biscoito de arroz", category:"carb", kcal:387, prot:8, carb:81, fat:2.8, mealTypes:["cafe","lanche"], subGroup:"pao" },
  { id:"c52", name:"Cereal de milho sem açúcar", category:"carb", kcal:370, prot:7, carb:84, fat:1.2, mealTypes:["cafe","lanche"], subGroup:"cereal_cafe" },
  { id:"c53", name:"Pera", category:"carb", kcal:57, prot:0.4, carb:15.2, fat:0.1, mealTypes:["cafe","lanche","jantar_adj"], subGroup:"fruta" },
  { id:"c54", name:"Kiwi", category:"carb", kcal:51, prot:1.1, carb:12.3, fat:0.4, mealTypes:["cafe","lanche","jantar_adj"], subGroup:"fruta" },
  { id:"c55", name:"Goiaba", category:"carb", kcal:54, prot:1.1, carb:13, fat:0.4, mealTypes:["cafe","lanche","jantar_adj"], subGroup:"fruta" },
  { id:"c56", name:"Melão", category:"carb", kcal:29, prot:0.7, carb:7.5, fat:0.1, mealTypes:["cafe","lanche","jantar_adj"], subGroup:"fruta" },
  { id:"c57", name:"Granola sem açúcar", category:"carb", kcal:405, prot:10.5, carb:61.2, fat:13.4, mealTypes:["cafe","lanche"], subGroup:"cereal_cafe" },
  { id:"c58", name:"Batata baroa cozida", category:"carb", kcal:80, prot:0.9, carb:19.6, fat:0.2, mealTypes:["principal"], subGroup:"tuberculo" },
  { id:"c59", name:"Cará cozido", category:"carb", kcal:96, prot:1.5, carb:22.5, fat:0.1, mealTypes:["principal"], subGroup:"tuberculo" },
  { id:"c60", name:"Arroz basmati cozido", category:"carb", kcal:121, prot:3.2, carb:25.2, fat:0.4, mealTypes:["principal"], subGroup:"arroz" },
  { id:"c61", name:"Batata bolinha cozida", category:"carb", kcal:68, prot:1.6, carb:15.7, fat:0.1, mealTypes:["principal"], subGroup:"tuberculo" },
  { id:"c62", name:"Purê de batata", category:"carb", kcal:88, prot:1.8, carb:15.6, fat:2.2, mealTypes:["principal"], subGroup:"tuberculo" },
  { id:"c63", name:"Nhoque de batata cozido", category:"carb", kcal:130, prot:3.8, carb:27, fat:1.1, mealTypes:["principal"], subGroup:"massa" },
  { id:"c64", name:"Cevadinha cozida", category:"carb", kcal:123, prot:2.3, carb:28.2, fat:0.4, mealTypes:["principal"], subGroup:"cereal" },
  { id:"c65", name:"Trigo para quibe cozido", category:"carb", kcal:83, prot:3.1, carb:18.6, fat:0.2, mealTypes:["principal"], subGroup:"cereal" },
  { id:"c66", name:"Cuscuz marroquino cozido", category:"carb", kcal:112, prot:3.8, carb:23.2, fat:0.2, mealTypes:["principal"], subGroup:"cereal" },
  { id:"c67", name:"Tortilha de trigo", category:"carb", kcal:310, prot:8.4, carb:50, fat:8.2, mealTypes:["lanche","principal"], subGroup:"pao" },
  { id:"c68", name:"Rap10 integral", category:"carb", kcal:286, prot:8.5, carb:45, fat:8.4, mealTypes:["lanche","principal"], subGroup:"pao" },
  { id:"c69", name:"Pão australiano", category:"carb", kcal:280, prot:8.5, carb:49, fat:5.2, mealTypes:["cafe","lanche"], subGroup:"pao" },
  { id:"c70", name:"Pão de centeio", category:"carb", kcal:259, prot:8.5, carb:48, fat:3.3, mealTypes:["cafe","lanche"], subGroup:"pao" },
  { id:"c71", name:"Tâmara seca", category:"carb", kcal:282, prot:2.5, carb:75, fat:0.4, mealTypes:["cafe","lanche"], subGroup:"fruta" },
  { id:"c72", name:"Damasco seco", category:"carb", kcal:241, prot:3.4, carb:63, fat:0.5, mealTypes:["cafe","lanche"], subGroup:"fruta" },
  { id:"c73", name:"Ameixa seca", category:"carb", kcal:240, prot:2.2, carb:64, fat:0.4, mealTypes:["cafe","lanche"], subGroup:"fruta" },
  { id:"c74", name:"Blueberry", category:"carb", kcal:57, prot:0.7, carb:14.5, fat:0.3, mealTypes:["cafe","lanche","jantar_adj"], subGroup:"fruta" },
  { id:"c75", name:"Framboesa", category:"carb", kcal:52, prot:1.2, carb:12, fat:0.7, mealTypes:["cafe","lanche","jantar_adj"], subGroup:"fruta" },
  { id:"c76", name:"Pêssego", category:"carb", kcal:39, prot:0.9, carb:9.5, fat:0.3, mealTypes:["cafe","lanche","jantar_adj"], subGroup:"fruta" },
  { id:"c77", name:"Abóbora cabotiá", category:"carb", kcal:48, prot:1.4, carb:10.8, fat:0.7, mealTypes:["principal"], subGroup:"legume" },
  { id:"c78", name:"Chuchu cozido", category:"carb", kcal:19, prot:0.4, carb:4.8, fat:0.1, mealTypes:["principal"], subGroup:"legume" },
  { id:"c79", name:"Abobrinha cozida", category:"carb", kcal:19, prot:1.1, carb:3.9, fat:0.2, mealTypes:["principal"], subGroup:"legume" },
  { id:"c80", name:"Lasanha de abobrinha", category:"carb", kcal:96, prot:5.8, carb:8.2, fat:4.8, mealTypes:["principal"], subGroup:"legume" },

  // === FATS ===
  { id:"f1", name:"Azeite de oliva", category:"fat", kcal:884, prot:0, carb:0, fat:100, mealTypes:["principal","cafe","lanche"], subGroup:"oleo" },
  { id:"f2", name:"Óleo de coco", category:"fat", kcal:862, prot:0, carb:0, fat:100, mealTypes:["cafe","principal"], subGroup:"oleo" },
  { id:"f3", name:"Manteiga s/ sal", category:"fat", kcal:726, prot:0.8, carb:0.1, fat:82.4, mealTypes:["cafe"], subGroup:"manteiga" },
  { id:"f4", name:"Pasta de amendoim", category:"fat", kcal:594, prot:25.3, carb:17.6, fat:49.4, mealTypes:["cafe","lanche"], subGroup:"oleaginosa_pasta" },
  { id:"f5", name:"Castanha-do-pará", category:"fat", kcal:643, prot:14.5, carb:12.3, fat:63.5, mealTypes:["lanche","cafe"], subGroup:"oleaginosa" },
  { id:"f6", name:"Castanha de caju", category:"fat", kcal:570, prot:18.5, carb:29.1, fat:46.3, mealTypes:["lanche","cafe"], subGroup:"oleaginosa" },
  { id:"f7", name:"Amendoim torrado", category:"fat", kcal:589, prot:27.2, carb:12.5, fat:49.2, mealTypes:["lanche"], subGroup:"oleaginosa" },
  { id:"f8", name:"Nozes", category:"fat", kcal:620, prot:14, carb:18.4, fat:59.4, mealTypes:["lanche","cafe"], subGroup:"oleaginosa" },
  { id:"f9", name:"Amêndoas", category:"fat", kcal:581, prot:18.6, carb:29.5, fat:47.3, mealTypes:["lanche","cafe"], subGroup:"oleaginosa" },
  { id:"f10", name:"Abacate", category:"fat", kcal:96, prot:1.2, carb:6, fat:8.4, mealTypes:["cafe","lanche","principal"], subGroup:"fruta_gord" },
  { id:"f11", name:"Creme de leite", category:"fat", kcal:202, prot:2.4, carb:3.7, fat:20.2, mealTypes:["principal"], subGroup:"laticinio_gord" },
  { id:"f12", name:"Queijo parmesão", category:"fat", kcal:453, prot:35.6, carb:1.7, fat:33.5, mealTypes:["principal"], subGroup:"queijo_gord" },
  { id:"f13", name:"Queijo muçarela", category:"fat", kcal:330, prot:22.6, carb:3, fat:25.2, mealTypes:["cafe","principal"], subGroup:"queijo_gord" },
  { id:"f14", name:"Chocolate amargo 70%", category:"fat", kcal:528, prot:6, carb:42, fat:38, mealTypes:["lanche"], subGroup:"outro" },
  { id:"f15", name:"Coco ralado seco", category:"fat", kcal:592, prot:5.7, carb:26.4, fat:54.7, mealTypes:["cafe","lanche"], subGroup:"coco" },
  { id:"f16", name:"Linhaça", category:"fat", kcal:495, prot:14.1, carb:43.3, fat:32.3, mealTypes:["cafe","lanche"], subGroup:"semente" },
  { id:"f17", name:"Chia", category:"fat", kcal:486, prot:16.5, carb:42.1, fat:30.7, mealTypes:["cafe","lanche"], subGroup:"semente" },
  { id:"f18", name:"Semente de girassol", category:"fat", kcal:570, prot:20.8, carb:20, fat:49.8, mealTypes:["lanche"], subGroup:"semente" },
  { id:"f19", name:"Azeite de dendê", category:"fat", kcal:884, prot:0, carb:0, fat:100, mealTypes:["principal"], subGroup:"oleo" },
  { id:"f20", name:"Tahine (gergelim)", category:"fat", kcal:595, prot:17, carb:21.2, fat:53.8, mealTypes:["lanche","cafe"], subGroup:"semente" },
  { id:"f21", name:"Requeijão cremoso", category:"fat", kcal:257, prot:7.5, carb:2.4, fat:24.5, mealTypes:["cafe","lanche"], subGroup:"laticinio_gord" },
  { id:"f22", name:"Azeitona preta", category:"fat", kcal:140, prot:1, carb:4.8, fat:13, mealTypes:["principal"], subGroup:"outro" },
  { id:"f23", name:"Macadâmia", category:"fat", kcal:718, prot:7.9, carb:13.8, fat:75.8, mealTypes:["lanche"], subGroup:"oleaginosa" },
  { id:"f24", name:"Pistache torrado", category:"fat", kcal:562, prot:20.2, carb:27.2, fat:45.3, mealTypes:["lanche"], subGroup:"oleaginosa" },
  { id:"f25", name:"Leite de coco", category:"fat", kcal:197, prot:1.4, carb:3.1, fat:21.3, mealTypes:["principal","cafe"], subGroup:"coco" },
  { id:"f26", name:"Manteiga de cacau", category:"fat", kcal:884, prot:0, carb:0, fat:100, mealTypes:["cafe"], subGroup:"manteiga" },
  { id:"f27", name:"Cream cheese", category:"fat", kcal:342, prot:6.2, carb:3.5, fat:34.2, mealTypes:["cafe","lanche"], subGroup:"laticinio_gord" },
  { id:"f28", name:"Ghee", category:"fat", kcal:900, prot:0, carb:0, fat:99.8, mealTypes:["cafe","principal"], subGroup:"manteiga" },
  { id:"f29", name:"Gordura de coco", category:"fat", kcal:862, prot:0, carb:0, fat:100, mealTypes:["cafe","principal"], subGroup:"oleo" },
  { id:"f30", name:"Avelã", category:"fat", kcal:646, prot:15, carb:16.7, fat:60.8, mealTypes:["lanche","cafe"], subGroup:"oleaginosa" },
  { id:"f31", name:"Semente de abóbora", category:"fat", kcal:446, prot:30.2, carb:10.7, fat:35.4, mealTypes:["lanche"], subGroup:"semente" },
  { id:"f32", name:"Queijo provolone", category:"fat", kcal:351, prot:25.6, carb:2.1, fat:26.6, mealTypes:["cafe","principal"], subGroup:"queijo_gord" },
  { id:"f33", name:"Gema de ovo", category:"fat", kcal:352, prot:16.1, carb:1.6, fat:31.9, mealTypes:["cafe"], subGroup:"ovo" },
  { id:"f34", name:"Queijo brie", category:"fat", kcal:334, prot:20.8, carb:0.5, fat:27.7, mealTypes:["cafe","lanche"], subGroup:"queijo_gord" },
  { id:"f35", name:"Bacon", category:"fat", kcal:541, prot:37, carb:0.1, fat:42, mealTypes:["cafe","principal"], subGroup:"suina" },
  { id:"f36", name:"Mix de nuts", category:"fat", kcal:607, prot:17, carb:20, fat:52, mealTypes:["lanche"], subGroup:"oleaginosa" },
  { id:"f37", name:"Óleo de abacate", category:"fat", kcal:884, prot:0, carb:0, fat:100, mealTypes:["principal"], subGroup:"oleo" },
  { id:"f38", name:"Queijo coalho", category:"fat", kcal:320, prot:21.5, carb:2, fat:25, mealTypes:["cafe","principal"], subGroup:"queijo_gord" },
  { id:"f39", name:"Manteiga de amendoim", category:"fat", kcal:588, prot:25, carb:20, fat:50, mealTypes:["cafe","lanche"], subGroup:"oleaginosa_pasta" },
  { id:"f40", name:"Coco fresco", category:"fat", kcal:354, prot:3.3, carb:15.2, fat:33.5, mealTypes:["lanche"], subGroup:"coco" },
  { id:"f41", name:"Pecã", category:"fat", kcal:691, prot:9.2, carb:13.9, fat:72, mealTypes:["lanche","cafe"], subGroup:"oleaginosa" },
  { id:"f42", name:"Castanha de baru", category:"fat", kcal:560, prot:24, carb:15, fat:44, mealTypes:["lanche","cafe"], subGroup:"oleaginosa" },
  { id:"f43", name:"Pinhão", category:"fat", kcal:174, prot:3, carb:37, fat:1, mealTypes:["lanche"], subGroup:"outro" },
  { id:"f44", name:"Coco chips", category:"fat", kcal:640, prot:6.5, carb:24, fat:58, mealTypes:["lanche","cafe"], subGroup:"coco" },
  { id:"f45", name:"Pasta de castanha de caju", category:"fat", kcal:594, prot:18, carb:27, fat:46, mealTypes:["cafe","lanche"], subGroup:"oleaginosa_pasta" },
  { id:"f46", name:"Pasta de amêndoas", category:"fat", kcal:614, prot:21, carb:19, fat:55, mealTypes:["cafe","lanche"], subGroup:"oleaginosa_pasta" },
  { id:"f47", name:"Pasta de pistache", category:"fat", kcal:590, prot:20, carb:24, fat:48, mealTypes:["cafe","lanche"], subGroup:"oleaginosa_pasta" },
  { id:"f48", name:"Manteiga de girassol", category:"fat", kcal:617, prot:17, carb:23, fat:55, mealTypes:["cafe","lanche"], subGroup:"semente" },
  { id:"f49", name:"Molho pesto", category:"fat", kcal:462, prot:4.6, carb:6.2, fat:47.3, mealTypes:["principal"], subGroup:"oleo" },
  { id:"f50", name:"Queijo prato", category:"fat", kcal:360, prot:22.7, carb:1.9, fat:29.1, mealTypes:["cafe","principal"], subGroup:"queijo_gord" },
  { id:"f51", name:"Queijo gouda", category:"fat", kcal:356, prot:24.9, carb:2.2, fat:27.4, mealTypes:["cafe","principal"], subGroup:"queijo_gord" },
  { id:"f52", name:"Azeitona verde", category:"fat", kcal:137, prot:1, carb:3.8, fat:13.3, mealTypes:["principal"], subGroup:"outro" },
  { id:"f53", name:"Semente de gergelim", category:"fat", kcal:573, prot:17.7, carb:23.4, fat:49.7, mealTypes:["lanche","cafe"], subGroup:"semente" },
  { id:"f54", name:"Linhaça dourada", category:"fat", kcal:490, prot:14.5, carb:42.6, fat:31.5, mealTypes:["lanche","cafe"], subGroup:"semente" },
  { id:"f55", name:"Óleo de gergelim", category:"fat", kcal:884, prot:0, carb:0, fat:100, mealTypes:["principal"], subGroup:"oleo" },
  { id:"f56", name:"Tahine integral", category:"fat", kcal:601, prot:17.2, carb:21, fat:54.6, mealTypes:["lanche","cafe"], subGroup:"semente" },
  { id:"f57", name:"Creme de amendoim integral", category:"fat", kcal:585, prot:24.5, carb:19.8, fat:49.3, mealTypes:["cafe","lanche"], subGroup:"oleaginosa_pasta" },
  { id:"f58", name:"Pinoli", category:"fat", kcal:673, prot:13.7, carb:13.1, fat:68.4, mealTypes:["lanche","cafe"], subGroup:"oleaginosa" },
  { id:"f59", name:"Pasta de macadâmia", category:"fat", kcal:720, prot:8.1, carb:12.2, fat:74.5, mealTypes:["cafe","lanche"], subGroup:"oleaginosa_pasta" },
  { id:"f60", name:"Óleo de linhaça", category:"fat", kcal:884, prot:0, carb:0, fat:100, mealTypes:["principal"], subGroup:"oleo" },
  { id:"f61", name:"Banha suína", category:"fat", kcal:902, prot:0, carb:0, fat:100, mealTypes:["principal"], subGroup:"suina" },
  { id:"f62", name:"Sebo bovino", category:"fat", kcal:902, prot:0, carb:0, fat:100, mealTypes:["principal"], subGroup:"bovina" },
  { id:"f63", name:"Manteiga com sal", category:"fat", kcal:717, prot:0.9, carb:0.1, fat:81, mealTypes:["cafe","principal"], subGroup:"manteiga" },
  { id:"f64", name:"Nata", category:"fat", kcal:300, prot:2.3, carb:3.1, fat:30, mealTypes:["cafe","lanche"], subGroup:"laticinio_gord" },
  { id:"f65", name:"Queijo cheddar", category:"fat", kcal:403, prot:24.9, carb:1.3, fat:33.1, mealTypes:["cafe","lanche","principal"], subGroup:"queijo_gord" },
  { id:"f66", name:"Queijo gorgonzola", category:"fat", kcal:353, prot:21.4, carb:2.3, fat:28.7, mealTypes:["principal","lanche"], subGroup:"queijo_gord" },
  { id:"f67", name:"Queijo meia cura", category:"fat", kcal:380, prot:25, carb:2.2, fat:30, mealTypes:["cafe","lanche","principal"], subGroup:"queijo_gord" },
  { id:"f68", name:"Queijo canastra", category:"fat", kcal:390, prot:24, carb:2, fat:32, mealTypes:["cafe","lanche"], subGroup:"queijo_gord" },
  { id:"f69", name:"Torresmo", category:"fat", kcal:544, prot:61, carb:0, fat:31, mealTypes:["principal","lanche"], subGroup:"suina" },
  { id:"f70", name:"Panceta assada", category:"fat", kcal:518, prot:24, carb:0, fat:46, mealTypes:["principal"], subGroup:"suina" },
  { id:"f71", name:"Maionese caseira", category:"fat", kcal:680, prot:1, carb:1, fat:75, mealTypes:["principal","lanche"], subGroup:"outro" },
  { id:"f72", name:"Creme de ricota", category:"fat", kcal:180, prot:8, carb:4, fat:14, mealTypes:["cafe","lanche"], subGroup:"laticinio_gord" },
  { id:"f73", name:"Requeijão light", category:"fat", kcal:180, prot:9, carb:3.2, fat:14, mealTypes:["cafe","lanche"], subGroup:"laticinio_gord" },
  { id:"f74", name:"Óleo MCT", category:"fat", kcal:884, prot:0, carb:0, fat:100, mealTypes:["cafe","lanche"], subGroup:"oleo" },
  { id:"f75", name:"Azeite trufado", category:"fat", kcal:884, prot:0, carb:0, fat:100, mealTypes:["principal"], subGroup:"oleo" },
  { id:"f76", name:"Pasta de avelã sem açúcar", category:"fat", kcal:650, prot:14, carb:18, fat:61, mealTypes:["cafe","lanche"], subGroup:"oleaginosa_pasta" },
  { id:"f77", name:"Amêndoa laminada", category:"fat", kcal:579, prot:21, carb:22, fat:50, mealTypes:["cafe","lanche"], subGroup:"oleaginosa" },
  { id:"f78", name:"Farinha de amêndoas", category:"fat", kcal:571, prot:21, carb:21, fat:50, mealTypes:["cafe","lanche"], subGroup:"oleaginosa" },
  { id:"f79", name:"Semente de cânhamo", category:"fat", kcal:553, prot:31.6, carb:8.7, fat:48.8, mealTypes:["cafe","lanche"], subGroup:"semente" },
  { id:"f80", name:"Óleo de macadâmia", category:"fat", kcal:884, prot:0, carb:0, fat:100, mealTypes:["principal"], subGroup:"oleo" },
];

const CARB_GI_BY_ID = {
  c1: "alto",
  c2: "medio",
  c3: "baixo",
  c4: "alto",
  c5: "medio",
  c6: "medio",
  c7: "baixo",
  c8: "alto",
  c9: "medio",
  c10: "baixo",
  c11: "medio",
  c12: "medio",
  c13: "medio",
  c14: "baixo",
  c15: "baixo",
  c16: "alto",
  c17: "medio",
  c18: "medio",
  c19: "medio",
  c20: "baixo",
  c21: "medio",
  c22: "alto",
  c23: "baixo",
  c24: "alto",
  c25: "baixo",
  c26: "baixo",
  c27: "baixo",
  c28: "alto",
  c29: "medio",
  c30: "medio",
  c31: "baixo",
  c32: "baixo",
  c33: "medio",
  c34: "medio",
  c35: "medio",
  c36: "medio",
  c37: "alto",
  c38: "baixo",
  c39: "baixo",
  c40: "baixo",
  c41: "medio",
  c42: "alto",
  c43: "medio",
  c44: "baixo",
  c45: "baixo",
  c46: "baixo",
  c47: "baixo",
  c48: "baixo",
  c49: "medio",
  c50: "medio",
  c51: "alto",
  c52: "alto",
  c53: "baixo",
  c54: "baixo",
  c55: "baixo",
  c56: "baixo",
  c57: "medio",
  c58: "alto",
  c59: "medio",
  c60: "medio",
  c61: "medio",
  c62: "alto",
  c63: "alto",
  c64: "baixo",
  c65: "medio",
  c66: "medio",
  c67: "medio",
  c68: "medio",
  c69: "medio",
  c70: "baixo",
  c71: "medio",
  c72: "baixo",
  c73: "baixo",
  c74: "baixo",
  c75: "baixo",
  c76: "baixo",
  c77: "baixo",
  c78: "baixo",
  c79: "baixo",
  c80: "baixo",
};

const ACCESSORY_IDS = new Set([
  "p32", "p35", "p38", "p39", "p40",
  "c11", "c13", "c14", "c15", "c22", "c23", "c25", "c26", "c27", "c36", "c37", "c38", "c39", "c40", "c46", "c47", "c48", "c53", "c54", "c55", "c56",
  "f11", "f14", "f19", "f22", "f25", "f43", "f49", "f52",
]);

const FLEX_IDS = new Set([
  "p3", "p14", "p22", "p33", "p34", "p36",
  "p54", "p55", "p56", "p57", "p59", "p60",
  "c10", "c17", "c21", "c30", "c31", "c32", "c33", "c34", "c44", "c45", "c49", "c50", "c57", "c60",
  "f15", "f16", "f17", "f20", "f21", "f27", "f31", "f40", "f44", "f48", "f53", "f54", "f56",
  "f59",
]);

const STRICT_CARNIVORE_SUBGROUPS = new Set([
  "ave_magra", "ave", "bovina_magra", "bovina", "peixe_magro", "peixe_gordo", "peixe", "frutos_mar", "suina", "outra", "frio", "embutido", "manteiga",
]);

const CARNIVORE_WITH_EGGS_DAIRY_SUBGROUPS = new Set([
  ...STRICT_CARNIVORE_SUBGROUPS,
  "ovo", "queijo", "queijo_magro", "queijo_gord", "laticinio", "laticinio_gord",
]);

function getDietTags(food) {
  const tags = ["traditional"];
  if (STRICT_CARNIVORE_SUBGROUPS.has(food.subGroup)) {
    tags.push("carnivore", "carnivore_eggs_dairy");
  } else if (CARNIVORE_WITH_EGGS_DAIRY_SUBGROUPS.has(food.subGroup)) {
    tags.push("carnivore_eggs_dairy");
  }
  return tags;
}

const foodsWithPlanningRole = foods.map((food) => ({
  ...food,
  dietTags: getDietTags(food),
  glycemicIndexLevel: food.category === "carb" ? (CARB_GI_BY_ID[food.id] || "medio") : null,
  planningRole: ACCESSORY_IDS.has(food.id) ? "accessory" : FLEX_IDS.has(food.id) ? "flex" : "core",
}));

const recipes = [
  {
    id: "r1",
    name: "Wrap de frango desfiado com requeijão",
    description: "Wrap integral com frango desfiado e requeijão cremoso.",
    mealTypes: ["lanche", "principal"],
    dietTags: ["traditional"],
    ingredients: [{ foodId: "c34", grams: 60 }, { foodId: "p26", grams: 120 }, { foodId: "f21", grams: 25 }],
  },
  {
    id: "r2",
    name: "Omelete com queijo minas",
    description: "Ovos com queijo minas para cafe ou lanche.",
    mealTypes: ["cafe", "lanche"],
    dietTags: ["traditional", "carnivore_eggs_dairy"],
    ingredients: [{ foodId: "p18", grams: 100 }, { foodId: "p21", grams: 40 }, { foodId: "f3", grams: 5 }],
  },
  {
    id: "r3",
    name: "Prato carnívoro bovino",
    description: "Patinho com ovos e manteiga para uma refeição sem vegetais.",
    mealTypes: ["principal"],
    dietTags: ["carnivore_eggs_dairy"],
    ingredients: [{ foodId: "p4", grams: 180 }, { foodId: "p18", grams: 100 }, { foodId: "f3", grams: 10 }],
  },
  {
    id: "r4",
    name: "Prato carnívoro estrito",
    description: "Contrafilé com bacon, sem ovos e sem laticínios.",
    mealTypes: ["principal"],
    dietTags: ["carnivore", "carnivore_eggs_dairy"],
    ingredients: [{ foodId: "p66", grams: 180 }, { foodId: "f35", grams: 35 }],
  },
  {
    id: "r5",
    name: "Bowl de arroz, frango e legumes",
    description: "Base tradicional com arroz, frango, cenoura e azeite.",
    mealTypes: ["principal"],
    dietTags: ["traditional"],
    ingredients: [{ foodId: "c1", grams: 140 }, { foodId: "p1", grams: 150 }, { foodId: "c27", grams: 70 }, { foodId: "f1", grams: 8 }],
  },
  {
    id: "r6",
    name: "Iogurte com whey e banana",
    description: "Lanche proteico rápido com iogurte, whey e fruta.",
    mealTypes: ["cafe", "lanche"],
    dietTags: ["traditional"],
    ingredients: [{ foodId: "p22", grams: 170 }, { foodId: "p24", grams: 30 }, { foodId: "c11", grams: 90 }],
  },
  {
    id: "r7",
    name: "Tilápia com batata e azeite",
    description: "Refeição tradicional leve com peixe, tubérculo e gordura.",
    mealTypes: ["principal"],
    dietTags: ["traditional"],
    ingredients: [{ foodId: "p12", grams: 180 }, { foodId: "c3", grams: 220 }, { foodId: "f1", grams: 10 }],
  },
  {
    id: "r8",
    name: "Lanche de queijo, presunto e ovos",
    description: "Opção sem grãos para carnívora com ovos e laticínios.",
    mealTypes: ["cafe", "lanche"],
    dietTags: ["carnivore_eggs_dairy"],
    ingredients: [{ foodId: "p18", grams: 100 }, { foodId: "p33", grams: 50 }, { foodId: "f65", grams: 30 }],
  },
  {
    id: "r9",
    name: "Frango com arroz integral e azeite",
    description: "Prato tradicional simples para almoço ou jantar.",
    mealTypes: ["principal"],
    dietTags: ["traditional"],
    ingredients: [{ foodId: "p43", grams: 160 }, { foodId: "c2", grams: 150 }, { foodId: "f1", grams: 8 }],
  },
  {
    id: "r10",
    name: "Patinho com mandioca e legumes",
    description: "Refeição tradicional com carne magra, carbo-base e legume.",
    mealTypes: ["principal"],
    dietTags: ["traditional"],
    ingredients: [{ foodId: "p4", grams: 150 }, { foodId: "c5", grams: 180 }, { foodId: "c79", grams: 80 }, { foodId: "f1", grams: 8 }],
  },
  {
    id: "r11",
    name: "Café de iogurte, aveia e morango",
    description: "Opção tradicional para café da manhã ou lanche.",
    mealTypes: ["cafe", "lanche"],
    dietTags: ["traditional"],
    ingredients: [{ foodId: "p56", grams: 170 }, { foodId: "c10", grams: 35 }, { foodId: "c39", grams: 100 }],
  },
  {
    id: "r12",
    name: "Tilápia com arroz basmati e abóbora",
    description: "Refeição tradicional leve com peixe e carboidratos de prato.",
    mealTypes: ["principal"],
    dietTags: ["traditional"],
    ingredients: [{ foodId: "p12", grams: 180 }, { foodId: "c60", grams: 150 }, { foodId: "c77", grams: 100 }, { foodId: "f1", grams: 8 }],
  },
  {
    id: "r13",
    name: "Picanha com sebo bovino",
    description: "Prato carnívoro estrito com corte bovino e gordura animal.",
    mealTypes: ["principal"],
    dietTags: ["carnivore", "carnivore_eggs_dairy"],
    ingredients: [{ foodId: "p63", grams: 190 }, { foodId: "f62", grams: 12 }],
  },
  {
    id: "r14",
    name: "Salmão com panceta",
    description: "Refeição carnívora estrita com peixe gordo e panceta.",
    mealTypes: ["principal"],
    dietTags: ["carnivore", "carnivore_eggs_dairy"],
    ingredients: [{ foodId: "p13", grams: 180 }, { foodId: "f70", grams: 35 }],
  },
  {
    id: "r15",
    name: "Hambúrguer bovino com bacon",
    description: "Opção carnívora estrita prática para refeição principal ou lanche.",
    mealTypes: ["principal", "lanche"],
    dietTags: ["carnivore", "carnivore_eggs_dairy"],
    ingredients: [{ foodId: "p80", grams: 180 }, { foodId: "f35", grams: 25 }],
  },
  {
    id: "r16",
    name: "Ovos mexidos com queijo e nata",
    description: "Café ou lanche carnívoro com ovos e laticínios.",
    mealTypes: ["cafe", "lanche"],
    dietTags: ["carnivore_eggs_dairy"],
    ingredients: [{ foodId: "p18", grams: 150 }, { foodId: "f65", grams: 30 }, { foodId: "f64", grams: 25 }],
  },
  {
    id: "r17",
    name: "Frango com creme de ricota",
    description: "Prato animal com frango, creme de ricota e manteiga.",
    mealTypes: ["principal"],
    dietTags: ["carnivore_eggs_dairy"],
    ingredients: [{ foodId: "p43", grams: 180 }, { foodId: "f72", grams: 45 }, { foodId: "f3", grams: 8 }],
  },
  {
    id: "r18",
    name: "Queijo coalho com presunto e ovos",
    description: "Lanche sem grãos para carnívora com ovos e laticínios.",
    mealTypes: ["cafe", "lanche"],
    dietTags: ["carnivore_eggs_dairy"],
    ingredients: [{ foodId: "p18", grams: 100 }, { foodId: "p33", grams: 60 }, { foodId: "f38", grams: 45 }],
  },
];

function getRecipeMacros(recipe, foodMap) {
  return recipe.ingredients.reduce((acc, ingredient) => {
    const food = foodMap.get(ingredient.foodId);
    if (!food) return acc;
    const ratio = ingredient.grams / 100;
    acc.kcal += food.kcal * ratio;
    acc.prot += food.prot * ratio;
    acc.carb += food.carb * ratio;
    acc.fat += food.fat * ratio;
    return acc;
  }, { kcal: 0, prot: 0, carb: 0, fat: 0 });
}

async function main() {
  console.log("Seeding TACO database...");
  
  // Upsert all foods
  for (const food of foodsWithPlanningRole) {
    await prisma.food.upsert({
      where: { id: food.id },
      update: food,
      create: food,
    });
  }
  
  console.log(`Seeded ${foodsWithPlanningRole.length} foods.`);

  const foodMap = new Map(foodsWithPlanningRole.map((food) => [food.id, food]));
  for (const recipe of recipes) {
    const macros = getRecipeMacros(recipe, foodMap);
    await prisma.recipe.upsert({
      where: { id: recipe.id },
      update: {
        ...recipe,
        kcal: Math.round(macros.kcal),
        prot: Number(macros.prot.toFixed(1)),
        carb: Number(macros.carb.toFixed(1)),
        fat: Number(macros.fat.toFixed(1)),
      },
      create: {
        ...recipe,
        kcal: Math.round(macros.kcal),
        prot: Number(macros.prot.toFixed(1)),
        carb: Number(macros.carb.toFixed(1)),
        fat: Number(macros.fat.toFixed(1)),
      },
    });
  }

  console.log(`Seeded ${recipes.length} recipes.`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
